/**
 * \copyright Copyright (c) 2021-2024 Infineon Technologies AG.
 *            All rights reserved.
 *
 * \copyright This document contains proprietary information. Passing on and
 *            copying of this document and communication of its contents is not
 *            permitted without prior written authorization.
 *
 *\file      ram_fw.h
 *\brief     Header file providing access to the scrambled content of RAM FW to be transferred by a batch of Load FW commands.
 *\author    IFAT DCL ATV SC D RAD CSFW FW
 *\date      08.05.2025
 *\warning   Autogenerated file - do not edit!
 */


#ifndef RAM_FW_H
#define RAM_FW_H

#include <stdint.h>

#ifdef __cplusplus
namespace IfxRfe_Ctrx8191_B11
{
#endif

#define TOT_NUM_OF_FRAMES 185u
#define MAX_CODE_WORDS    30u

typedef struct
{
    uint8_t key1;
    uint8_t length;
    uint32_t key2;
    uint32_t key3;
    uint32_t code_word[MAX_CODE_WORDS];
} t_load_fw_spi_frame;

extern const t_load_fw_spi_frame scrambled_fw_spi_frame[TOT_NUM_OF_FRAMES];

#ifdef __cplusplus
} // namespace IfxRfe_Ctrx8191_B11
#endif

#endif
